### ISSUE TITLE
Add convenience instances for 7 day, 1 day, etc

### ISSUE THREAD

**Issue by timkpaine** [airflow-laminar/airflow-supervisor#125]
"Always on 7 day"

```yaml
stop_on_exit: false
cleanup: false
stop_on_exit: false
cleanup: false
restart_on_initial: true
restart_on_retrigger: false
airflow:
    _target_: airflow_supervisor.AirflowConfiguration
    runtime: 604800 # 60 * 60 * 24 * 7
    check_interval: 30
    check_timeout: 28800 # 60 * 60 * 8
```

"8/12 Hour"

```yaml
cleanup: false
airflow:
    _target_: airflow_supervisor.AirflowConfiguration
    runtime: 43200 # 60 * 60 * 12
    endtime: 20:00:00
    maxretrigger: 10
    check_interval: 30
    check_timeout: 28800 # 60 * 60 * 8
```
