### ISSUE TITLE
Split ssh config, add pass through of ssh operator parameters

### ISSUE THREAD

**Issue by timkpaine** [airflow-laminar/airflow-supervisor#47]
Example Config:
```yaml
_target_: airflow_supervisor.SupervisorSSHAirflowConfiguration

airflow:
  _target_: airflow_supervisor.AirflowConfiguration
  host: HOSTNAME
  port: '*:8000'
  rpcinterface_factory: supervisor.rpcinterface:make_main_rpcinterface
  local_or_remote: remote

program:
  sleep:
    _target_: airflow_supervisor.ProgramConfiguration
    command: sleep 1000

cmd_timeout: 3600
working_dir: /tmp/supervisor
config_path: /tmp/supervisor/supervisord.conf
```
