### ISSUE TITLE
Ensure commands are properly shell-escaped when converting pydantic model to json

### ISSUE THREAD

**Issue by timkpaine** [airflow-laminar/airflow-supervisor#60]
```
program:
  test:
    _target_: airflow_supervisor.ProgramConfiguration
    command: "bash -c 'sleep 14400; exit 1'"
```
